import { EarthlyBranch } from '@iching-kt/provider-time';

interface BranchInfo {
  chinese: string;
  pinyin: string;
  animal: string;
  timeRange: string;
  element: string;
  yinYang: 'yin' | 'yang';
  organ: string;
  description: string;
  activity: string;
}

type Translations = {
  [lang: string]: {
    branches: Record<EarthlyBranch, BranchInfo>;
    labels: {
      currentHour: string;
      timeRange: string;
      element: string;
      animal: string;
      organ: string;
      activity: string;
      description: string;
      shichen: string;
      sovereignHexagram: string;
    };
  };
};

export const translations: Translations = {
  en: {
    labels: {
      currentHour: 'Current Hour',
      timeRange: 'Time Range',
      element: 'Element',
      animal: 'Animal',
      organ: 'Meridian',
      activity: 'Auspicious Activity',
      description: 'Description',
      shichen: 'Shichen',
      sovereignHexagram: 'Sovereign Hexagram',
    },
    branches: {
      zi: {
        chinese: '子',
        pinyin: 'zǐ',
        animal: 'Rat',
        timeRange: '23:00-01:00',
        element: 'Water',
        yinYang: 'yang',
        organ: 'Gallbladder',
        description: 'The Rat thrives in midnight stillness. Qi begins its cycle anew.',
        activity: 'Deep rest, dream work, meditation',
      },
      chou: {
        chinese: '丑',
        pinyin: 'chǒu',
        animal: 'Ox',
        timeRange: '01:00-03:00',
        element: 'Earth',
        yinYang: 'yin',
        organ: 'Liver',
        description: 'The Ox works steadily in darkness. The liver cleanses and restores blood.',
        activity: 'Deep sleep, liver detoxification',
      },
      yin: {
        chinese: '寅',
        pinyin: 'yín',
        animal: 'Tiger',
        timeRange: '03:00-05:00',
        element: 'Wood',
        yinYang: 'yang',
        organ: 'Lungs',
        description: 'The Tiger awakens before dawn. Lungs distribute Qi throughout the body.',
        activity: 'Deep breathing, early rising for monks',
      },
      mao: {
        chinese: '卯',
        pinyin: 'mǎo',
        animal: 'Rabbit',
        timeRange: '05:00-07:00',
        element: 'Wood',
        yinYang: 'yin',
        organ: 'Large Intestine',
        description: 'The Rabbit emerges at dawn. Time for elimination and cleansing.',
        activity: 'Wake naturally, bowel movement, light exercise',
      },
      chen: {
        chinese: '辰',
        pinyin: 'chén',
        animal: 'Dragon',
        timeRange: '07:00-09:00',
        element: 'Earth',
        yinYang: 'yang',
        organ: 'Stomach',
        description: 'The Dragon brings morning energy. Stomach Qi is at its peak.',
        activity: 'Eat a hearty breakfast, begin important work',
      },
      si: {
        chinese: '巳',
        pinyin: 'sì',
        animal: 'Snake',
        timeRange: '09:00-11:00',
        element: 'Fire',
        yinYang: 'yin',
        organ: 'Spleen',
        description: 'The Snake coils in warming sun. Spleen transforms food into energy.',
        activity: 'Mental work, study, decision-making',
      },
      wu: {
        chinese: '午',
        pinyin: 'wǔ',
        animal: 'Horse',
        timeRange: '11:00-13:00',
        element: 'Fire',
        yinYang: 'yang',
        organ: 'Heart',
        description: 'The Horse gallops at midday peak. Heart Qi and Yang reach maximum.',
        activity: 'Light lunch, brief rest, social interaction',
      },
      wei: {
        chinese: '未',
        pinyin: 'wèi',
        animal: 'Goat',
        timeRange: '13:00-15:00',
        element: 'Earth',
        yinYang: 'yin',
        organ: 'Small Intestine',
        description: 'The Goat grazes peacefully. Small intestine sorts pure from impure.',
        activity: 'Digest and absorb, gentle activities',
      },
      shen: {
        chinese: '申',
        pinyin: 'shēn',
        animal: 'Monkey',
        timeRange: '15:00-17:00',
        element: 'Metal',
        yinYang: 'yang',
        organ: 'Bladder',
        description: 'The Monkey is most alert now. Bladder stores and releases fluids.',
        activity: 'Peak efficiency, exercise, study retention',
      },
      you: {
        chinese: '酉',
        pinyin: 'yǒu',
        animal: 'Rooster',
        timeRange: '17:00-19:00',
        element: 'Metal',
        yinYang: 'yin',
        organ: 'Kidneys',
        description: 'The Rooster calls day\'s end. Kidneys store vital essence.',
        activity: 'Light dinner, complete work, socializing',
      },
      xu: {
        chinese: '戌',
        pinyin: 'xū',
        animal: 'Dog',
        timeRange: '19:00-21:00',
        element: 'Earth',
        yinYang: 'yang',
        organ: 'Pericardium',
        description: 'The Dog guards the home at dusk. Pericardium protects the heart.',
        activity: 'Relaxation, intimacy, emotional connection',
      },
      hai: {
        chinese: '亥',
        pinyin: 'hài',
        animal: 'Pig',
        timeRange: '21:00-23:00',
        element: 'Water',
        yinYang: 'yin',
        organ: 'Triple Burner',
        description: 'The Pig rests contentedly. Triple Burner balances all systems.',
        activity: 'Prepare for sleep, quiet reflection',
      },
    },
  },
  es: {
    labels: {
      currentHour: 'Hora Actual',
      timeRange: 'Rango Horario',
      element: 'Elemento',
      animal: 'Animal',
      organ: 'Meridiano',
      activity: 'Actividad Propicia',
      description: 'Descripción',
      shichen: 'Shichen',
      sovereignHexagram: 'Hexagrama Soberano',
    },
    branches: {
      zi: {
        chinese: '子',
        pinyin: 'zǐ',
        animal: 'Rata',
        timeRange: '23:00-01:00',
        element: 'Agua',
        yinYang: 'yang',
        organ: 'Vesícula Biliar',
        description: 'La Rata prospera en la quietud de medianoche. El Qi inicia su ciclo.',
        activity: 'Descanso profundo, trabajo onírico, meditación',
      },
      chou: {
        chinese: '丑',
        pinyin: 'chǒu',
        animal: 'Buey',
        timeRange: '01:00-03:00',
        element: 'Tierra',
        yinYang: 'yin',
        organ: 'Hígado',
        description: 'El Buey trabaja en la oscuridad. El hígado limpia y restaura la sangre.',
        activity: 'Sueño profundo, desintoxicación hepática',
      },
      yin: {
        chinese: '寅',
        pinyin: 'yín',
        animal: 'Tigre',
        timeRange: '03:00-05:00',
        element: 'Madera',
        yinYang: 'yang',
        organ: 'Pulmones',
        description: 'El Tigre despierta antes del alba. Los pulmones distribuyen el Qi.',
        activity: 'Respiración profunda, despertar temprano',
      },
      mao: {
        chinese: '卯',
        pinyin: 'mǎo',
        animal: 'Conejo',
        timeRange: '05:00-07:00',
        element: 'Madera',
        yinYang: 'yin',
        organ: 'Intestino Grueso',
        description: 'El Conejo emerge al alba. Tiempo de eliminación y limpieza.',
        activity: 'Despertar natural, evacuación, ejercicio suave',
      },
      chen: {
        chinese: '辰',
        pinyin: 'chén',
        animal: 'Dragón',
        timeRange: '07:00-09:00',
        element: 'Tierra',
        yinYang: 'yang',
        organ: 'Estómago',
        description: 'El Dragón trae energía matutina. El Qi del estómago está en su pico.',
        activity: 'Desayuno abundante, iniciar trabajo importante',
      },
      si: {
        chinese: '巳',
        pinyin: 'sì',
        animal: 'Serpiente',
        timeRange: '09:00-11:00',
        element: 'Fuego',
        yinYang: 'yin',
        organ: 'Bazo',
        description: 'La Serpiente se enrosca al sol. El bazo transforma alimento en energía.',
        activity: 'Trabajo mental, estudio, toma de decisiones',
      },
      wu: {
        chinese: '午',
        pinyin: 'wǔ',
        animal: 'Caballo',
        timeRange: '11:00-13:00',
        element: 'Fuego',
        yinYang: 'yang',
        organ: 'Corazón',
        description: 'El Caballo galopa en el pico del día. El Qi del corazón es máximo.',
        activity: 'Almuerzo ligero, breve descanso, socializar',
      },
      wei: {
        chinese: '未',
        pinyin: 'wèi',
        animal: 'Cabra',
        timeRange: '13:00-15:00',
        element: 'Tierra',
        yinYang: 'yin',
        organ: 'Intestino Delgado',
        description: 'La Cabra pasta tranquila. El intestino delgado separa lo puro.',
        activity: 'Digerir y absorber, actividades suaves',
      },
      shen: {
        chinese: '申',
        pinyin: 'shēn',
        animal: 'Mono',
        timeRange: '15:00-17:00',
        element: 'Metal',
        yinYang: 'yang',
        organ: 'Vejiga',
        description: 'El Mono está más alerta ahora. La vejiga almacena y libera fluidos.',
        activity: 'Máxima eficiencia, ejercicio, retención de estudio',
      },
      you: {
        chinese: '酉',
        pinyin: 'yǒu',
        animal: 'Gallo',
        timeRange: '17:00-19:00',
        element: 'Metal',
        yinYang: 'yin',
        organ: 'Riñones',
        description: 'El Gallo anuncia el fin del día. Los riñones guardan la esencia vital.',
        activity: 'Cena ligera, completar trabajo, socializar',
      },
      xu: {
        chinese: '戌',
        pinyin: 'xū',
        animal: 'Perro',
        timeRange: '19:00-21:00',
        element: 'Tierra',
        yinYang: 'yang',
        organ: 'Pericardio',
        description: 'El Perro guarda el hogar al anochecer. El pericardio protege el corazón.',
        activity: 'Relajación, intimidad, conexión emocional',
      },
      hai: {
        chinese: '亥',
        pinyin: 'hài',
        animal: 'Cerdo',
        timeRange: '21:00-23:00',
        element: 'Agua',
        yinYang: 'yin',
        organ: 'Triple Calentador',
        description: 'El Cerdo descansa contento. El Triple Calentador equilibra todos los sistemas.',
        activity: 'Prepararse para dormir, reflexión tranquila',
      },
    },
  },
  zh: {
    labels: {
      currentHour: '當前時辰',
      timeRange: '時間範圍',
      element: '五行',
      animal: '生肖',
      organ: '經絡',
      activity: '宜事',
      description: '說明',
      shichen: '時辰',
      sovereignHexagram: '消息卦',
    },
    branches: {
      zi: {
        chinese: '子',
        pinyin: 'zǐ',
        animal: '鼠',
        timeRange: '23:00-01:00',
        element: '水',
        yinYang: 'yang',
        organ: '膽經',
        description: '子時陽氣初生，萬物靜謐。宜養膽經，深睡為佳。',
        activity: '深度休息、夢境修行、靜坐冥想',
      },
      chou: {
        chinese: '丑',
        pinyin: 'chǒu',
        animal: '牛',
        timeRange: '01:00-03:00',
        element: '土',
        yinYang: 'yin',
        organ: '肝經',
        description: '丑時肝經當令，臥血歸肝。宜熟睡養肝，排毒解鬱。',
        activity: '深度睡眠、肝臟排毒',
      },
      yin: {
        chinese: '寅',
        pinyin: 'yín',
        animal: '虎',
        timeRange: '03:00-05:00',
        element: '木',
        yinYang: 'yang',
        organ: '肺經',
        description: '寅時肺經當令，氣血始布。宜深呼吸，養肺清氣。',
        activity: '深呼吸、修行者早起',
      },
      mao: {
        chinese: '卯',
        pinyin: 'mǎo',
        animal: '兔',
        timeRange: '05:00-07:00',
        element: '木',
        yinYang: 'yin',
        organ: '大腸經',
        description: '卯時大腸當令，宜排便通暢。日出而作，舒展筋骨。',
        activity: '自然醒、排便、輕度運動',
      },
      chen: {
        chinese: '辰',
        pinyin: 'chén',
        animal: '龍',
        timeRange: '07:00-09:00',
        element: '土',
        yinYang: 'yang',
        organ: '胃經',
        description: '辰時胃經當令，消化力強。宜豐盛早餐，開始重要工作。',
        activity: '豐盛早餐、開始重要工作',
      },
      si: {
        chinese: '巳',
        pinyin: 'sì',
        animal: '蛇',
        timeRange: '09:00-11:00',
        element: '火',
        yinYang: 'yin',
        organ: '脾經',
        description: '巳時脾經當令，運化水穀。宜思考決策，精神集中。',
        activity: '腦力工作、學習、決策',
      },
      wu: {
        chinese: '午',
        pinyin: 'wǔ',
        animal: '馬',
        timeRange: '11:00-13:00',
        element: '火',
        yinYang: 'yang',
        organ: '心經',
        description: '午時心經當令，陽氣至極。宜輕食小憩，養心安神。',
        activity: '輕食午餐、小憩、社交',
      },
      wei: {
        chinese: '未',
        pinyin: 'wèi',
        animal: '羊',
        timeRange: '13:00-15:00',
        element: '土',
        yinYang: 'yin',
        organ: '小腸經',
        description: '未時小腸當令，分清泌濁。宜消化吸收，緩和活動。',
        activity: '消化吸收、緩和活動',
      },
      shen: {
        chinese: '申',
        pinyin: 'shēn',
        animal: '猴',
        timeRange: '15:00-17:00',
        element: '金',
        yinYang: 'yang',
        organ: '膀胱經',
        description: '申時膀胱當令，排毒代謝。宜運動學習，效率最高。',
        activity: '最高效率、運動、記憶學習',
      },
      you: {
        chinese: '酉',
        pinyin: 'yǒu',
        animal: '雞',
        timeRange: '17:00-19:00',
        element: '金',
        yinYang: 'yin',
        organ: '腎經',
        description: '酉時腎經當令，藏精納氣。宜輕食收工，養腎固本。',
        activity: '輕食晚餐、收工、社交',
      },
      xu: {
        chinese: '戌',
        pinyin: 'xū',
        animal: '狗',
        timeRange: '19:00-21:00',
        element: '土',
        yinYang: 'yang',
        organ: '心包經',
        description: '戌時心包當令，護心安神。宜放鬆情緒，增進親密。',
        activity: '放鬆、親密關係、情感交流',
      },
      hai: {
        chinese: '亥',
        pinyin: 'hài',
        animal: '豬',
        timeRange: '21:00-23:00',
        element: '水',
        yinYang: 'yin',
        organ: '三焦經',
        description: '亥時三焦當令，百脈皆通。宜安神靜養，準備入眠。',
        activity: '準備入睡、靜心反思',
      },
    },
  },
};

export function getTranslation(lang: string) {
  return translations[lang] || translations.en;
}
